version: '3'
services:
  vue-3-mega-menu:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8088:8088"
    container_name: vue-3-mega-menu
    volumes:
      - .:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules